### ISSUE TITLE
CRYPTOBALANCE with ADA (Cardano) wallets not working

### ISSUE THREAD

**Issue by hyomocha** [Eloise1988/CRYPTOBALANCE#1]
I believe the issue is related to the length of the public key, which I believe is at 104 characters long. Every other currency wallet I have tested works well, but their keys are much shorter.

I'm not much of a programmer, so I hope this description helps.

**Comment by Eloise1988** [comment]
There seems to be a timeout issue. It takes too long for the software to process the cardano blockchain. Thanks for letting me know, I tried to find a solution using different technics but I still haven't figured it out. I will let you know if/when it works properly.

**Comment by hyomocha** [comment]
Yeah no worries. I'm not a programmer and so didn't know how to
troubleshoot it myself. Glad I could be of assistance.

Have a great day!

**Comment by GrandGarcon** [comment]
Hi @Eloise1988  , taking into consideration that its the issue of  performance ( i.e as  CRYPTOTOOLS.js shows , first your backend of site fetches the data from the blockchain  service ( or from third party site) ---> then you have to do the processing of data by running the code  and that also interacting with the API of the google drive / sheets , which indeed will creates huge lag , and thus  there is timeout due to production of next block and thus creating data inconsistency . so there can be two solutions 

1. either store the  API requests as an array  , which are not currently served by the backend , and then using async process to upgrade them when we get the data. while at the same time , another worker process will be  sending the fetch calls to the backend at the regular time intervals < timeout time  ( actually i am not sure of this idea  , but i came accross it randomly ).

2. to make changes in the architecture , making it serverless . by taking following approach :
   - creating your script to run on google apps script , thats the serverless platform to run the  js functions on the google services ( drive , excel sheet etc)
  -  we can follow the tutorials like : https://dev.to/a0viedo/writing-to-a-google-sheet-using-serverless-2ndc . 

in general , that will be great to scale it also . i will try to implement the both and then create PR . 

hope it helps 

Dhruv

**Comment by Eloise1988** [comment]
> I believe the issue is related to the length of the public key, which I believe is at 104 characters long. Every other currency wallet I have tested works well, but their keys are much shorter.
> 
> I'm not much of a programmer, so I hope this description helps.

The issue has been resolved. You can retrieve ADA (Cardano)balances

**Comment by ty-han** [comment]
Hi.  My attempts at pulling ADA balances consistently time out with "Exceeded maximum execution time (line 0)".  Other coins work fine.  Is it still working for you all?

**Comment by Eloise1988** [comment]
Hi,

I tried multiple ADA addresses and they all seem to work fine on my side. For example I just tried this:
![image](https://user-images.githubusercontent.com/53000607/136711039-84fe4288-b98a-4506-b4b2-341fc6eafcc8.png)

https://explorer.cardano.org/en/address.html?address=addr1q9wm3gx67w7s2uru398ezpw5mm9vz2yx8xhykdnyxw6hkpaexh3k8kznmelkczm344arw7tjsrmy4zk4zqnhydqjl6sstrkazp

=cryptobalance("ada","addr1q9wm3gx67w7s2uru398ezpw5mm9vz2yx8xhykdnyxw6hkpaexh3k8kznmelkczm344arw7tjsrmy4zk4zqnhydqjl6sstrkazp")

I wonder if it's an address issue, is the above formula working on your sheet?

**Comment by ty-han** [comment]
My bad.  I had copied and pasted a formula from the cell above that used a contract address for the lookup.  Now it works, with the correct formula.  Thank you for your help though!

**Comment by danicuki** [comment]
ADA Balance is not working for me... is there any special configuration for that?

**Comment by danicuki** [comment]
A simple function to retrieve ADA Balance
```
async function ADABalance(stake_address) {
  var res = await UrlFetchApp.fetch("https://cardanoscan.io/stakekey/" + stake_address);
  var content = res.getContentText();  
  return Number(content.match(/adaAmount\>([0-9]*)\</)[1]) / 1000000;
}
```
