### ISSUE TITLE
Access latest DEX pairs directly via CURL?

### ISSUE THREAD

**Issue by j-greig** [Eloise1988/CRYPTOBALANCE#21]
I have the CRYPTOLATESTPAIRS working nicely in a Google Sheet but would like to directly query the API endpoint.

Using an approach similar to the below I get 301 Moved Permanently errors. 

Should this be possible or am I barking up the wrong tree?

`curl -X GET "https://privateapi.cryptotools.one/UNISWAPFILTER/2/10000/20000/20/privatekeyhere" -H "accept: application/json"`

Have also tried curl `curl -X GET "hhttps://privateapi.charmantadvisory.com/PAIRSFILTER2/10000/20000/20/privatekeyhere" -H "accept: application/json" -H "apikey: privatekeyhere"`

**Comment by j-greig** [comment]
Ah, is it because I'm using the testing key and need to go premium?

**Comment by Eloise1988** [comment]
In order to access CRYPTOLATESTPAIRS you need to use a private key.
 curl -X GET  should work with the key.
 
CryptoTools Pro
The premium version offers two options for you to choose from:

1 - Up to 50,000 calls per month for only $8.99 per month
2 - Unlimited calls per month for just $14.99 per month
If you're interested in upgrading to the premium version, please let me know and I'll be happy to assist you further.
