### ISSUE TITLE
My wallet address always show 0 balance although there is some money inside

### ISSUE THREAD

**Issue by yanrs17** [Eloise1988/CRYPTOBALANCE#4]
Does anyone else also have this problem or it is just me?

**Comment by Eloise1988** [comment]
If it's a hot wallet on a centralized exchange, it's normal you can't see the amount since exchange use tags for users but have all the coins on the same address, the exchange address.

If that's not your case, you need to give me more info on the cryptocurrency that is not working anymore. Could be that I need to update some code for certain cryptocurrencies.
