### ISSUE TITLE
Google Sheets Error: "Exceeded maximum execution time (line 0)."

### ISSUE THREAD

**Issue by aidenmarcoux** [Eloise1988/CRYPTOBALANCE#7]
I am getting:
"Error
Exceeded maximum execution time (line 0)." 

Seems like this is an issue on the example sheet too. So maybe just not on my end.

**Comment by kjspring** [comment]
My executions are failing. It seems like the time limit is exceeding 30 seconds.

**Comment by bowlingotter** [comment]
Same issue here

**Comment by adrienbarreau** [comment]
I got the same error, logged it and here is what I got.

`Exception: Service invoked too many times for one day: urlfetch`

Seems like the script is doing too many API calls.

**Comment by Eloise1988** [comment]
#faq exceeded API limits 

Google Sheets has API limits. 
For Google Limits:
https://developers.google.com/sheets/api/limits
https://developers.google.com/apps-script/guides/services/quotas

![image](https://user-images.githubusercontent.com/53000607/132490549-339edb85-afb9-4d37-a644-0e28b0da8951.png)

If you want to trouble shoot the functions to see where it goes wrong, a first step is to go and app-script and get the error message which should give you more information.

Limits are per account not per sheet.

Functions will go back to normal in a couple of hours when Google resets your daily limits. 

Tips:
1- delete all formulas that have duplicates and reference  just one of them instead of calling 10 times the same formula
2- batch refreshes into multiple calls of 20. Google limits with max 30 formulas at once.
3-check in spreadsheet setting/calculation/recalculation is on change uniquely
4- check in tools/script editor/overview your overall function consumption with error rate. It will guide you on understanding where you stand in terms of limits with Google
5- getting a premium account on Google also helps but you are still limited.. https://developers.google.com/apps-script/guides/services/quotas
6- It could also probably help if you had a checkbox which all formulas run on (if(checkbox=true, cryptobalance(..)). Then just untick before closing the sheet so that the calls don't run in the background. Example: =if(Overview!$O$2=true,CRYPTOBALANCE(...),"Tick refresh box"). I just tick the box when I open the sheet and then all the data loads. Then I untick before I close it.

These points should help you limit the #ERROR maximum execution exceeded.

FYI: The limitations don't come from my API. Currently, there are NO limits for my users. I don't have any partnership with GOOGLE.

When you get errors and think Cryptotools functions are down, you can check their operational status here:
https://stats.uptimerobot.com/NWoqAINy4q

Make sure you have the latest version of code:
CRYPTOTOOLS:
https://raw.githubusercontent.com/Eloise1988/CRYPTOBALANCE/master/CRYPTOTOOLS_V2.gs

COINGECKO:
https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs
